# Felipe Veloso Desafio 12

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('seaborn-whitegrid')
plt.rcParams['figure.figsize'] = (10,6)

# Desafío 1: Prepare el ambiente de trabajo

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [17]:
df = pd.read_csv('boston.csv');
df = df.drop('Unnamed: 0' , axis=1)

In [18]:
df.describe()

crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677082   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio       black  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat        medv  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

# Desafío 2: División de la muestra

In [19]:
y_vec = df['medv']
X_mat = df.drop('medv', axis=1)

In [22]:
X_train, X_test , y_train , y_test = train_test_split(X_mat ,y_vec,test_size=.33 , random_state=3322)

# Desafío 3: Generación de modelos

In [37]:
norm_model = LinearRegression(fit_intercept=True,normalize=True).fit(X_train,y_train).predict(X_test)

In [41]:
norm_model

array([33.11301423, 16.24645418, 18.19262246, -5.64352315, 21.5323601 ,
       23.03332756, 41.02012272, 20.18293344, 14.27978301, 20.89167895,
       24.793581  , 30.83824004, 28.25114947, 11.57803698, 23.31232912,
       13.92947579, 36.30700399, 16.05992031, 29.80017731, 31.50423742,
       35.74878147, 27.38208921, 18.84246725, 18.90622865, 27.190364  ,
       25.71466841, 30.78327414, 21.32944466,  7.34546802, 20.89339572,
       20.0860902 , 36.69315778, 40.88890736, 37.20714354, 24.03571648,
       12.80652446, 21.15923575, 31.92735963, 42.15207826, 23.8360389 ,
       37.93031347, 22.77261714, 12.32128836, 22.74431323, 27.58400927,
       28.75712158, 19.61698794, 19.28570277, 34.26614384, 14.85075256,
       14.09151393, 13.63847302, 18.89242906, 32.98745893, 15.28683875,
       13.2757103 , 22.45274485,  9.47474366, 16.3782865 , 24.02529003,
       13.92868183, 19.72917157, 16.72992947, 35.55027182, 21.30962533,
       19.00945167, 25.83977106, 25.1139756 , 12.47691763, 29.01

In [39]:
non_norm_model = LinearRegression(fit_intercept=False , normalize=False).fit(X_train,y_train).predict(X_test)

In [42]:
non_norm_model

array([32.61340199, 18.47259825, 17.69461337, -6.7085615 , 20.92627142,
       22.22382882, 42.64934455, 21.92124915, 13.89690425, 21.06257204,
       25.80747899, 30.61116666, 27.55457509, 11.09882636, 22.80673904,
       15.95135697, 37.2179477 , 16.04871278, 30.80153936, 31.97671958,
       35.15392229, 26.82265572, 19.85807872, 19.95885174, 24.39764047,
       25.00449768, 30.68663823, 20.34980831,  7.81896222, 20.81026779,
       19.21160386, 36.89678425, 40.70527473, 36.97727236, 22.27389339,
       13.0875059 , 22.84616429, 31.80561017, 43.42028321, 23.76971214,
       38.52890488, 21.79058627, 13.54559108, 22.45993528, 26.8674988 ,
       29.83041639, 19.11592721, 19.51792781, 33.81301591, 15.84460331,
       13.94206387, 14.08990553, 18.78306377, 33.15345664, 15.73763375,
       13.38261944, 21.74195032, 10.80125103, 17.49469922, 22.4645927 ,
       14.39423899, 20.68244575, 16.62857905, 34.95441378, 20.59217624,
       20.17654429, 25.14654974, 25.26094384, 13.33004649, 27.95

# Desafío 4: Obtención de métricas

In [43]:
def report_scores(Y_test,predict):
    mse_modelo = mean_squared_error(Y_test, predict).round(1)
    r2_modelo = r2_score(Y_test,predict).round(1)
    print(mse_modelo,r2_modelo)

In [44]:
report_scores(y_test,norm_model)

31.3 0.6


In [45]:
report_scores(y_test,non_norm_model)

35.4 0.6


El modelo normalizado, tiene un mejor Promedio Error Cuadratico por lo cual es un mejor modelo

# Desafío 5: Refactorización del modelo

In [50]:
def fetch_features(df , vector = 'medv'):
    columns = df.columns
    attr_name,pearson_r,abs_pearson_r = [],[],[]

    for col in columns:
        if col != vector:
            attr_name.append(col)
            pearson_r.append(df[col].corr(df[vector]))
            abs_pearson_r.append(abs(df[col].corr(df[vector])))
    features = pd.DataFrame(
        {'attribute': attr_name,
        'corr': pearson_r,
        'abs_corr': abs_pearson_r}
    )   

    features = features.set_index('attribute')
    return features.sort_values(by=['abs_corr'], ascending =False)

In [51]:
fetch_features(df,'medv')

corr  abs_corr
attribute                    
lstat     -0.737663  0.737663
rm         0.695360  0.695360
ptratio   -0.507787  0.507787
indus     -0.483725  0.483725
tax       -0.468536  0.468536
nox       -0.427321  0.427321
crim      -0.388305  0.388305
rad       -0.381626  0.381626
age       -0.376955  0.376955
zn         0.360445  0.360445
black      0.333461  0.333461
dis        0.249929  0.249929
chas       0.175260  0.175260

El modelo se ajusta bien con las variables, istat , rm ,ptratio,indus,tax,nox

# Desafío 6: Refactorización del modelo predictivo

In [53]:
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [59]:
df_opt = df.loc[:,['lstat','rm','ptratio','indus','tax','nox','medv']]

In [60]:
y_vec = df_opt['medv']
X_mat = df_opt.drop('medv', axis=1)

In [61]:
X_train, X_test , y_train , y_test = train_test_split(X_mat ,y_vec,test_size=.33 , random_state=553)

In [63]:
norm_model_opt = LinearRegression().fit(X_train,y_train).predict(X_test)

In [64]:
norm_model_opt

array([26.37863262, 11.18331235, 29.79466007, 26.86813327, 20.30257133,
       14.4590943 , 27.69365033, 27.58505116, 34.29875253, 17.70448631,
       12.60611427, 21.63913447, 19.26028303, 17.02209745, 34.88743797,
       24.92452573, 24.05780241, 12.91065287, 27.95799876, 24.83048992,
       27.58963296, 16.68852875, 42.43890933, 34.72846533, 19.23428291,
       31.18226155, 27.59934105, 20.56934517, 22.79598122, 30.02920031,
       29.88736225, 18.70973825, 22.74555563, 14.92894596, 12.34212188,
       30.93214538, 32.41503941, 24.98245636, 22.62842193, 28.84029878,
       19.33946212, 24.25844585, 21.56599567, 40.57192662, 22.63211442,
       32.94497282, 21.60586681, 25.88368355, 18.54290928, 21.00516146,
       30.07440719, 20.83055067, 37.88284119, 17.23995776, 27.62968267,
       25.16119883, 16.7678885 , 31.66223187, 20.59137704,  9.9627843 ,
       25.30967005, 27.7399966 , 31.9393584 , 30.73801441, 37.04893752,
       27.86762392, 16.54872191, 31.0015025 , 21.11968237, 22.69

In [65]:
report_scores(y_test,norm_model_opt)

34.4 0.6
